import '../../../src/Kernel/Driver'
import '../../../src/Kernel/Drivers/ACPI'
import '../../../src/Kernel/Drivers/PIC'
import '../../../src/Kernel/Drivers/PIT'
import '../../../src/Kernel/Drivers/StivaleTags'
